### PR TITLE
pip check failure - "you have wordcloud 0.0.0"

### PR DESCRIPTION
**Pull request by rxm7706**
ydata-profiling 0.0.dev0 has requirement wordcloud>=1.9.3, but you have wordcloud 0.0.0 https://github.com/conda-forge/platformdirs-feedstock/pull/2/files https://github.com/conda-forge/tcolorpy-feedstock/pull/13/files https://github.com/conda-forge/ydata-profiling-feedstock/pull/34

Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

  - https://github.com/conda-forge/ydata-profiling-feedstock/pull/34#issuecomment-2508777590
  - ydata-profiling 0.0.dev0 has requirement wordcloud>=1.9.3, but you have wordcloud 0.0.0
  - https://github.com/conda-forge/platformdirs-feedstock/pull/2/files
  - https://github.com/conda-forge/tcolorpy-feedstock/pull/13/files
  - https://github.com/conda-forge/ydata-profiling-feedstock/pull/34

### CODE REVIEW

**Comment by rxm7706** [comment]
@conda-forge-admin, please rerender

**Comment by rxm7706** [comment]
@conda-forge-admin, please rerender

**Comment by rxm7706** [comment]
@conda-forge-admin, please rerender

**Comment by ocefpaf** [comment]
0 days since the last version 0.0.0 incident. Our record is 0 days.

**Pull request merged**
